language: java
jdk:
- oraclejdk8
sudo: false
scrpt: gradle/travis_build.sh
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
deploy:
  provider: bintray
  file: bintray.json
  user: $BINTRAY_USER
  key: $BINTRAY_API_KEY
  dry-run: false
